"""
State whether the following statements are True or False.
a. The exception handling mechanism is supposed to handle compile time errors. - False
b. It is necessary to declare the exception class within the class in which an exception going to be thrown. - False
c. Every raised exception must be caught. - True
d. For one try block there can be multiple except blocks. - True
e. When an exception is raised an exception class' constructor gets called. - True
f. try blocks cannot be nested. - False
g. Proper destruction of an object is guaranteed by exception handling mechanism. - True
h. All exceptions occur at runtime. - True
i. Exceptions offer an object-oriented way of handling runtime errors. - True
j. If an exception occurs, then the program terminates abruptly without getting any chance to recover from the exception. - False
k. No matter whether an exception occurs or not, the statements in the finally clause (if present) will get executed. - True
l. A program can contain multiple finally clauses. - True
m. finally clause is used to perform cleanup operations like closing the network/database connections. - True
n. While raising a user-defined exception multiple values can be set in the exception object. - True
o. In one function/method, there can be only one try block. - False
p. An exception must be caught in the same function/method in which it is raised. - False
q. All values set up in the exception object are available in the except block. - True
r. If our program does not catch an exception then the Python Runtime catches it. - True
s. It is possible to create user-defined exceptions. - True
t. All types of exceptions can be caught using the Exception class. - True
u. For every try block there must be a corresponding finally block. - False
"""